export const categoryContants = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
};

export const productContants = {
  GET_PRODUCTS_BY_SLUG: "GET_PRODUCTS_BY_SLUG",
  GET_PRODUCTS_PAGE_REQUEST: "GET_PRODUCTS_PAGE_REQUEST",
  GET_PRODUCTS_PAGE_SUCCESS: "GET_PRODUCTS_PAGE_SUCCESS",
  GET_PRODUCTS_PAGE_FAILURE: "GET_PRODUCTS_PAGE_FAILURE",

  GET_PRODUCT_DETAILS_BY_ID_REQUEST: "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",

  GET_PRODUCTS: "GET_PRODUCTS",

  ADD_REVIEW_REQUEST: "ADD_REVIEW_REQUEST",
  ADD_REVIEW_SUCCESS: "ADD_REVIEW_SUCCESS",
  ADD_REVIEW_FAILURE: "ADD_REVIEW_FAILURE",
};

export const discountContants = {
  GET_DISCOUNTS_BY_NAME: "GET_DISCOUNTS_BY_NAME",
  RESET_DISCOUNT: "RESET_DISCOUNT",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  CHANGE_INFO_REQUEST: "CHANGE_INFO_REQUEST",
  CHANGE_INFO_SUCCESS: "CHANGE_INFO_SUCCESS",
  CHANGE_INFO_FAILURE: "CHANGE_INFO_FAILURE",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};

export const wishConstants = {
  ADD_TO_WISH_REQUEST: "ADD_TO_WISH_REQUEST",
  ADD_TO_WISH_SUCCESS: "ADD_TO_WISH_SUCCESS",
  ADD_TO_WISH_FAILURE: "ADD_TO_WISH_FAILURE",
  RESET_WISH: "RESET_WISH",

  REMOVE_WISH_ITEM_REQUEST: "REMOVE_CART_WISH_REQUEST",
  REMOVE_WISH_ITEM_SUCCESS: "REMOVE_CART_WISH_SUCCESS",
  REMOVE_WISH_ITEM_FAILURE: "REMOVE_CART_WISH_FAILURE",
};

export const compareConstants = {
  ADD_TO_COMPARE_REQUEST: "ADD_TO_COMPARE_REQUEST",
  ADD_TO_COMPARE_SUCCESS: "ADD_TO_COMPARE_SUCCESS",
  ADD_TO_COMPARE_FAILURE: "ADD_TO_COMPARE_FAILURE",
  RESET_COMPARE: "RESET_COMPARE",

  REMOVE_COMPARE_ITEM_REQUEST: "REMOVE_CART_COMPARE_REQUEST",
  REMOVE_COMPARE_ITEM_SUCCESS: "REMOVE_CART_COMPARE_SUCCESS",
  REMOVE_COMPARE_ITEM_FAILURE: "REMOVE_CART_COMPARE_FAILURE",
};

export const userConstants = {
  GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
  GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
  GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
  ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
  ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
  ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
  ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
  ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
  ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

  GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
  GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
  GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

  GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
  GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
  GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
};

export const orderConstants = {
  UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
  UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
  UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",

  UPDATE_REVIEW_ORDER_REQUEST: "UPDATE_REVIEW_ORDER_REQUEST",
  UPDATE_REVIEW_ORDER_SUCCESS: "UPDATE_REVIEW_ORDER_SUCCESS",
  UPDATE_REVIEW_ORDER_FAILURE: "UPDATE_REVIEW_ORDER_FAILURE",
};
